### ISSUE TITLE
Enforce coding styles (prettier)

### ISSUE THREAD

**Issue by ekkolon** [swantzter/apollo-datasource-firestore#12]
As I intend to work on #6, I'd like to suggest enforcing coding styles 
using *prettier*. Perhaps in combo with [Google TypeScript Style](https://github.com/google/gts)

This would make future contributions more appealing and more consistent.
Maybe we can make that change first before moving on to feature PRs?

Otherwise, I'll leave it as it is and move on to implement #6.

What do you think @swantzter? Does this appeal to you, and if so, do you have any preset config
for prettier in mind?

**Comment by swantzter** [comment]
Personally, I think `eslint-config-standard-with-typescript` that the project currently uses works just fine and I don't really see a reason to change the code styles atm

**Comment by ekkolon** [comment]
Roger that!
