### ISSUE TITLE
Datasource typescript issues regarding CollectionReference type: error TS2322 & TS2345

### ISSUE THREAD

**Issue by bleams** [swantzter/apollo-datasource-firestore#15]
Hello, 
I recently installed the last version `v6.1.0` of your interesting package. I carefully followed the procedure described in your documentation. 
I am using `
"firebase": "^10.8.0",
"@apollo/server": "^4.8.1",
"typescript": "^5.1.6",
node v18.14.2
`

**_Can anyone help me solve these types issues ? Thanks by advance for your help_**

Here is the code on my side: 

`firestore-db.ts`

```js
import {initializeApp} from "firebase/app";
import {getFirestore} from "firebase/firestore";

// Initialize Firebase
const app = initializeApp(config);

// Initialize Cloud Firestore and get a reference to the service
export const db = getFirestore(app);
```

`Bars.ts`

``` js
import {collection,
    DocumentData,
    getDocs,
    Timestamp,
    CollectionReference,
} from "firebase/firestore";
import {FirestoreDataSource} from "apollo-datasource-firestore";
import {db} from "../firestore-db";

export interface BarsDoc {
    readonly id: string
    readonly collection: "bars"
    // the createdAt and updatedAt timestamps stored by firestore natively are
    // available as properties as well
    readonly createdAt: Timestamp
    readonly updatedAt: Timestamp
    drinks: []
}

export class BarsDataSource extends FirestoreDataSource<BarsDoc> {}

export const barsCollection: CollectionReference<BarsDoc> = collection(db, 'bars')
```
The `barsCollection` displays this error :
`TS2322: Type 'CollectionReference<DocumentData, DocumentData>' is not assignable to type 'CollectionReference<BarsDoc, DocumentData>'.   The types returned by 'converter.fromFirestore(...)' are incompatible between these types.     Type 'DocumentData' is not assignable to type 'BarsDoc'.`

`server/src/index.ts`

```js
expressMiddleware(server, {
            context: async ({req, res}) => {
                return {
                    dataSources: {
                        bars: new BarsDataSource(barsCollection),
                    }
                }
            },
        }),
```
Here, the error is:
`
TS2345: Argument of type 'CollectionReference<BarsDoc, DocumentData>' is not assignable to parameter of type 'CollectionReference<BarsDoc>'.   Type 'CollectionReference<BarsDoc, DocumentData>' is missing the following properties from type 'CollectionReference<BarsDoc>': listDocuments, doc, add, isEqual, and 14 more.'
`

<img width="1421" alt="image" src="https://github.com/swantzter/apollo-datasource-firestore/assets/3476324/50b32a7b-ee44-4d0d-83a0-da274a523bed">

**Comment by swantzter** [comment]
Hi, due to how the types are set up for firestore you have to mark the type with `as`:

```
export const barsCollection = collection(db, 'bars') as CollectionReference<BarsDoc>
```
