### ISSUE TITLE
automatic createdAt, updatedAt

### ISSUE THREAD

**Issue by swantzter** [swantzter/apollo-datasource-firestore#6]
we can use `dSnap.createTime` and `dSnap.updateTime` to extract these values in the transformer

**Comment by ekkolon** [comment]
Working on PR to add this feature, if you don't mind?!
Just for clarification, by "transformer" you mean the data converter handler (fromFirestore handler specifically), right?

**Comment by swantzter** [comment]
closed in 617964f3d4e2903f582d52eb27f74cf1733b053d
